development:
  consumer_key: 'ADgNLmaRC59nP9yx9JxwxvdSC'
  consumer_secret: '45WavQYUy8OoymckfsOKFrmcGZkL03cWZxEMMLufeUxo34vLsk'
  oauth_token: '21847307-3C2rZ69Yem9rAbwuOtpbGs7FS9nQjmxh21Z33f1fF'
  oauth_token_secret: 'F489O62wkxzYqJrU6nDAJob36nf1ANqX3ygaXANAIB6vg'